name: GitHub server installation

on:
  push:
  pull_request_target:
  workflow_dispatch:
    inputs:
      tags:
        required: False
        description: 'Optional. Use a "tag expression" specify which tagged tests to run (https://cucumber.io/docs/cucumber/api/#tag-expressions)'
      show_docker_output:
        required: false
        default: false
        type: boolean
        description: 'Show the docker logs while building the GitHub server container. It will also save the docker log artifact. This might show sensitive config information.'

jobs:

  github-server-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
      
    steps:
      # Place the root directory in this branch to access
      # relative paths to action files
      - uses: actions/checkout@v3

      - name: ALKiln - Start the isolated temporary docassemble server on GitHub
        id: github_server
        uses: suffolkLITLab/ALKiln/action_for_github_server@v5
      - run: echo "ALKiln finished starting the isolated GitHub docassemble server"
        shell: bash
      
      - name: Docker debug tmate session
        uses: mxschmitt/action-tmate@v3

      - name: "Run ALKiln tests"
        if: ${{ success() }}
        uses: suffolkLITLab/ALKiln@v5
        with:
          SERVER_URL: "${{ steps.github_server.outputs.SERVER_URL }}"
          DOCASSEMBLE_DEVELOPER_API_KEY: "${{ steps.github_server.outputs.DOCASSEMBLE_DEVELOPER_API_KEY }}"
          INSTALL_METHOD: "server"
          # ALKILN_TAG_EXPRESSION: @a_tag_expression
          # ALKILN_VERSION: 
